### ISSUE TITLE
Retrospectives not loading.. we are on the latest version

### ISSUE THREAD

**Issue by philipcj** [microsoft/vsts-extension-retrospectives#673]
I go into Azure Devops, click Boards, click Retrospectives and the page doesn't load.

I am using the new URL (dev.azure.com) not that this makes any difference.

The system needs ?teamid= adding to the URL to get it to work, which I get from another user.

There is nothing I can press in devops to make the retro board come up.

![image](https://github.com/microsoft/vsts-extension-retrospectives/assets/13755306/f44d15cb-8547-49de-89ac-4fcf342d2f1d)

This link works
https://dev.azure.com/InsuranceDataSolutions/Projects/_apps/hub/ms-devlabs.team-retrospectives.home?teamId=588f68cc-3a49-415d-94ed-f4a66fe27611&boardId=7b4e5cf8-2eaa-4f24-b6d6-a4cd6a540e68

This link does not

https://dev.azure.com/InsuranceDataSolutions/Projects/_apps/hub/ms-devlabs.team-retrospectives.home

**Comment by polatengin** [comment]
hi @philipcj , can we jump on a call and see the issue, please? I couldn't repro this issue on my environment. if you can share your email, I'll send you a Teams meeting request.

**Comment by polatengin** [comment]
I found the problem. there is an infinite loop, I'll fix it right-away and release a new version with the fix 👍

**Comment by polatengin** [comment]
I think I solved the issue, testing on a test environment now.. thanks for being patient!..

**Comment by polatengin** [comment]
it seems the issue is fixed with PR (#677)

closing this issue for now, if you see the issue continues, please feel free to re-open it 👍

**Comment by philipcj** [comment]
The problem isn’t resolved for me

**Comment by philipcj** [comment]
> hi @philipcj , can we jump on a call and see the issue, please? I couldn't repro this issue on my environment. if you can share your email, I'll send you a Teams meeting request.

Phil.johnson@insurancedatasolutions.co.uk thanks

**Comment by NivyaAgarwal** [comment]
Hello, we are using SaaS with Retrospective extension. It is at latest version but few of our users still facing issue with loading of the retrospective screen. Please suggest what could be the issue and fix. 

Contact : srideep.ganguly@husqvarnagroup.com

![MicrosoftTeams-image (3)](https://github.com/microsoft/vsts-extension-retrospectives/assets/148563571/3af80cc9-9e32-4d6c-9b5e-7c408726a5ff)

**Comment by annabelhammond** [comment]
Hi- same thing is happening for me
Contact: annabel.hammond@selwoodhousing.com

**Comment by philipcj** [comment]
Hi Annabel

The fix for me (from memory) was to turn everything on in the project settings I think I had both pipelines and artifacts turned off.

Anyway it worked when I turned everything on.

See below.

Hope this helps.

Phil
***@***.***

**Comment by annabelhammond** [comment]
Hey Phil,

Unfortunately that didn’t do the trick, History shows but doesn’t allow me to go anywhere when its open.

Any other tips?

Thanks!

***@***.***
Annabel Hammond‑Stevens​​​​
IT Solutions Development Manager
Selwood Housing
Tel:
01225715686<tel:01225715686>
Email:
***@***.******@***.***>
Web:
www.selwoodhousing.com<https://www.selwoodhousing.com/>
***@***.***<https://www.facebook.com/SelwoodHousing/>
***@***.***<https://www.linkedin.com/company/selwood-housing/>
***@***.***<https://twitter.com/selwoodhousing>
***@***.***
